//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yulius.Api.Helper.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiConfiguraciones_Rutas
    {
        public long Id { get; set; }
        public long IdApi { get; set; }
        public string Ruta { get; set; }
        public string Descripcion { get; set; }
        public string Identificador { get; set; }
    }
}
