//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yulius.Api.Helper.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiConfiguraciones
    {
        public long Id { get; set; }
        public string Uri { get; set; }
        public string Nombre { get; set; }
        public string Token { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string DirectorioVirtual { get; set; }
        public bool Visual { get; set; }
        public string RutaToken { get; set; }
        public int TipoSeguridad { get; set; }
        public string EncabezadoToken { get; set; }
        public string EncabezadoUsuario { get; set; }
        public string EncabezadoClave { get; set; }
        public string Prefijo { get; set; }
    }
}
